[package]
name = "camlet"
description = "Native Iced floating camera overlay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false
default-run = "camlet"

[dependencies]
bytemuck.workspace = true
camlet-camera = { path = "../camlet-camera", version = "=0.2.0" }
camlet-core = { path = "../camlet-core", version = "=0.2.0" }
directories.workspace = true
iced.workspace = true
num-traits.workspace = true
serde.workspace = true
serde_json.workspace = true
sys-locale.workspace = true
thiserror.workspace = true
webbrowser.workspace = true

[dev-dependencies]
iced_test = "0.14.0"
tempfile = "3.23.0"

[lints]
workspace = true
